server:
  port: 9526
  servlet:
    context-path: /feign
spring:
  application:
    name: nacos-feign
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: dev
        service: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

feign:
  hystrix:
    enabled: true