server:
  port: 9527
  servlet:
    context-path: /provide
spring:
  application:
    name: nacos-provide
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: dev
        service: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always